import {Inter} from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar/Sidebar";
import Header from "@/components/Header";
const inter = Inter({subsets: ["latin"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <div className="min-h-screen grid grid-cols-1 lg:grid-cols-6">
        {/* sidebar */}
        <Sidebar />
        {/* PANEL */}
        <div className="col-span-5">
          {/* <Header /> */}
          <Header />
          {/* contenido */}
          <div className={`bg-gray-100${inter.className}`}>{children}</div>
        </div>
      </div>
      {/* <body className={inter.className}>{children}</body> */}
    </html>
  );
}
